insert into categories values
('health care'),
('food and drink'),
('motor vehicles'),
('public transit'),
('taxes'),
('recreational drugs'),
('controlled substances'),
('firearms'),
('alcohol'),
('tobacco'),
('roadways'),
('education'),
('higher education'),
('city planning'),
('agriculture'),
('conservation'),
('law enforcement'),
('aviation'),
('fraud'),
('finance'),
('occupational safety'),
('accessibility'),
('mental health'),
('welfare'),
('legislation'),
('military'),
('veterans'),
('utilities'),
('cyber'),
('advertising'),
('pharma/medicine'),
('immigration'),
('intellectual property'),
('public services'),
('government reform'),
('workers rights'),
('infrastructure'),
('sports'),
('gambling'),
('energy'),
('domestic animals'),
('service animals'),
('religion')
